apiVersion: v1
kind: ConfigMap
metadata:
  name: env-cm
  namespace: locust
data:
  LOAD_URL: "http://www.google.com/"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: locustfile-cm
  namespace: locust
data:
  locustfile.py: |
    import time, os
    from locust import HttpUser, task, between, constant
    env_host = os.getenv("TARGET_HOST","https://www.google.com")

    class StandardUser(HttpUser):
        wait_time = constant(1)
        host = env_host

        @task
        def get_page(self):
            self.client.get("/", timeout=5)