apiVersion: v1
kind: Service
metadata:
  name: locust-service-nodeport
  namespace: locust
spec:
  type: NodePort
  selector:
    app: locust-master
  ports:
    - protocol: TCP
      port: 8089
      targetPort: 8089
---
kind: Service
apiVersion: v1
metadata:
  name: locust-master
  namespace: locust
  labels:
    app: locust-master
spec:
  type: ClusterIP
  ports:
    - port: 5557
      targetPort: loc-master-p1
      protocol: TCP
      name: loc-master-p1
    - port: 5558
      targetPort: loc-master-p2
      protocol: TCP
      name: loc-master-p2
  selector:
    app: locust-master
---
kind: Service
apiVersion: v1
metadata:
  name: locust-master-web
  namespace: locust
#  annotations:
#    networking.gke.io/load-balancer-type: "Internal"
  labels:
    app: locust-master
spec:
  type: LoadBalancer
  ports:
    - port: 8089
      targetPort: loc-master-web
      protocol: TCP
      name: loc-master-web
  selector:
    app: locust-master
