apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: locust-master
  namespace: locust
  labels:
    name: locust-master
spec:
  replicas: 1
  selector:
    matchLabels:
      app: locust-master
  template:
    metadata:
      labels:
        app: locust-master
    spec:
      volumes:
      - name: locustfile
        configMap:
          name: locustfile-cm
      containers:
        - name: locust-master
          image: locustio/locust:latest
          args: ["--master"]
          volumeMounts:
          - mountPath: /home/locust
            name: locustfile          
          ports:
            - name: loc-master-web
              containerPort: 8089
              protocol: TCP
            - name: loc-master-p1
              containerPort: 5557
              protocol: TCP
            - name: loc-master-p2
              containerPort: 5558
              protocol: TCP
          env:
            - name: LOCUST_MODE
              value: master
            - name: TARGET_HOST
              valueFrom:
                configMapKeyRef:
                  name: env-cm
                  key: LOAD_URL
      dnsPolicy: ClusterFirst
      restartPolicy: Always